name: 'Delete workflow runs'
description: 'An action to delete workflow runs in a repository.'
author: 'Bright Ran'

inputs:
  token:
    description: 'A personal access token (PAT) to authenticate.'
    required: true

  repository:
    description: 'The name of the repository.'
    required: true
    default: ${{ github.repository }}

  retain_days:
    description: 'The number of days.'
    required: true

runs:
  using: 'node12'
  main: 'dist/index.js'

branding:
  icon: 'delete'
  color: 'red'
